twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        img_dir: 'assets/uploads/'
        img_site: 'assets/img/'

when@test:
    twig:
        strict_variables: true
